### ISSUE TITLE
Position and Intensity of the Light Source

### ISSUE THREAD

**Issue by Jan-nik** [MarcelBrusius/Liter-Of-Light#10]
To create a realistic light source there are two quantities, we need to determine based on some credible references.

1. the angle of incidence of sunlight

1. the irradiance of sunlight

Both quantities may depend stronly on the time of day, so maybe it would be good to have them as a function dependant on the hour. Then we could make a seperate simulation for every hour. What do you think?

**Comment by MarcelBrusius** [comment]
Could be a good idea. Therefore, we would have to know the location of the sun during a day in regions where this project is actively used.

**Comment by Jan-nik** [comment]
I have used this website https://www.esrl.noaa.gov/gmd/grad/solcalc/azel.html to get angles for every hour of day. For the irradiance we still work with constant 1000W/m^2 right now.

**Comment by MarcelBrusius** [comment]
Concerning the website: Is something like this available for a broader range of cities like outside the US?

Concerning the irradiance: I'm still not completely satisfied with this model, because can we just use the full irradiance in just this tiny (in comparison) rectangle?

**Comment by Jan-nik** [comment]
On the website I collected the data for Venezuela, Caracas (16th June 2017). (Thats close to the equator, i thought, but in Venezuela "LiterofLight" is not active I think).

Irradiance is measured in W/m^2, so the size of the rectangle doesn't matter. To compute the radiant flux that is "emitted" by the rectangle, we just have to multiply with its size. But I'm concerned with a constant irradiance too, mainly because the atmosphere is dampening the irrandiance, and this dampening might depend on the angle of the sun. (For a low angle the sun rays have a longer travel distance inside the atmosphere.)

**Comment by MarcelBrusius** [comment]
I think this reduced radiance flux is neglectable, at least for the moment.
