### ISSUE TITLE
Optional Plots

### ISSUE THREAD

**Issue by Jan-nik** [MarcelBrusius/Liter-Of-Light#12]
Is it possible to avoid any plots before the whole simulation is finished, meaning to save all data relevant for plotting and only plot after a user request?

Marcel, I'm just assigning you to this because you did all the plotting and I'm a bit worried I'll ruin sth. :)

**Comment by MarcelBrusius** [comment]
Yes, we can. 🤣 

We just have to save the resulting refractions that leave the bottle in a Cell array.
