### ISSUE TITLE
Optimize 'RayTrace' performance

### ISSUE THREAD

**Issue by MarcelBrusius** [MarcelBrusius/Liter-Of-Light#4]
For each single ray, use its direction and the surface normals together with 'find' function to reduce the amount of boundary layers to examine.
Also distinguish incoming light rays and light rays that already have been refracted.

**Comment by Jan-nik** [comment]
In RayTrace, Codeline 32: if norm(...,2)<1

The condition checks if the origin vector of the light ray is closer than 1 to the nearest vertex of the bottle. But it should check whether the origin vector is inside or outside the bottle, right? Or is my RayTrace.m file not up to date?

**Comment by MarcelBrusius** [comment]
> it should check whether the origin vector is inside or outside the bottle

`norm(Light.Origin(raynum,:) - Surface.Bottle.Points(Surface.Bottle.nearestNeighbor(Light.Origin(raynum,:)),:),2) < 1`

exactly. But it is vulnerable to numerical instabilities due to solving linear systems. To circumvent this, I want to check if it is at least in a small ball (radius = 0.5) around the closest triangle vertex.

One may update this part of code by some criterion that depends on the overall scale of e.g. the bottle. But this is not of importance yet.

**Comment by Jan-nik** [comment]
Ok. The point exactly on the center bottom of the bottle is 4.5 away from all triangle vertices, so i think i will replace the "<1" by "<4.5".

I will also try some things to reduce computation time a bit, right now we are at ca. 0,07 sec per calculation of a hitting point for a single light ray.

**Comment by Jan-nik** [comment]
I tried to reduce computation time, but i only managed to double it :/
Well, I think for non-concav triangularizations our current algorithm is pretty much optimal.
