### ISSUE TITLE
Total reflaction produces error due to complex valued direction vectors

### ISSUE THREAD

**Issue by MarcelBrusius** [MarcelBrusius/Liter-Of-Light#5]

**Comment by MarcelBrusius** [comment]
Could you please take a look at the special case of a total reflection?

In addition, I use this formula since it allows computing both phenomena easily
[Snell's Law](http://www.thefullwiki.org/Snells_law)

**Comment by Nicolai46** [comment]
Yes, I'll work on it tomorrow. Additionally, I'll add the computation of the rates of reflection/refraction via the fresnel equations, which is needed to calculate the loss of intensity.
